### ISSUE TITLE
AttributeError in diff model

### ISSUE THREAD

**Issue by gabija-kavaliauskaite** [DeplanckeLab/ChromatinHD#7]
Hi, I am trying to set the ChromatinHD-diff model, but getting the AttributeError: module 'chromatinhd.models.diff.model' has no attribute 'cutnf'. 

The error can be resolved by importing cutnf itself 'from chromatinhd.models.diff.model import cutnf'

**Comment by zouter** [comment]
Ok, thank you! I'll fix this in the next version
